baseURL = 'https://duykhang0448.github.io/'
languageCode = 'en-us'
title = 'Hồ Duy Khang'

theme = 'gokarna-hugo'

[params]
  avatarAltText = "avatar"
  avatarSize = "size-m"
  avatarURL = "/images/khang.jpg"

  customHeadHTML = """
    <!-- KaTeX -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.css" integrity="sha384-Xi8rHCmBmhbuyyhbI88391ZKP2dmfnOl4rT9ZfRI7mLTdk1wblIUnrIq35nqwEvC" crossorigin="anonymous">
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.js" integrity="sha384-X/XCfMm41VSsqRNQgDerQczD69XqmjOOOwYQvr/uuC+j4OPoNhVgjdGFwhvN02Ja" crossorigin="anonymous"></script>
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/contrib/auto-render.min.js" integrity="sha384-+XBljXPPiv+OzfbB3cVmLHf4hdUFHlWNZN5spNQ7rmHTXpd7WvJum6fIACpNNfIR" crossorigin="anonymous"></script>
    <script>
      document.addEventListener("DOMContentLoaded", function() {
        renderMathInElement(document.body, {
          // customised options
          // • auto-render specific keys, e.g.:
          delimiters: [
            {left: '$$', right: '$$', display: true},
            {left: '$', right: '$', display: false},
          ],
          // • rendering keys, e.g.:
          throwOnError : false
        });
      });
    </script>
  """

  description = "Chào mừng bạn đến với trangtrang của tôi, nơi giới thiệu tiểu sử, kỹ năng và kinh nghiệm của tôi."
  author = "Hồ Duy Khang"
  jobTitle = "Lập trình viên"
  university = "Trường Đại học Công Nghệ Thành phố Hồ Chí Minh"
  footer = "Khang Hồ"
  metaKeywords = ["blog", "gokarna", "hugo"]
  showBackToTopButton = true # true or false for "back to top" button on posts and pages

  socialIcons = [
    {name = "facebook", url = "https://www.facebook.com/khang090803"},
    {name = "github", url = "https://github.com/duyKhang0448"},
    {name = "email", url = "mailto:hoduykha0448@gmail.com"}
  ]

[menu]
  [[menu.main]]
    name = "Trang chủ"
    pre = "<span data-feather='home'></span>"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Bài viết"
    pre = "<span data-feather='book'></span>"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    identifier = "github"
    pre = "<span data-feather='github'></span>"
    url = "https://github.com/duyKhang0448"
    weight = 5

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 4
    ordered = false

[minify]
    minifyOutput = true

